### PR TITLE
Added a simple for, no conditional behavior etc.

### LINKED ISSUE #25: Trying to use `for` throws an error.
A `for` of the form:

```clojure
(for [p start-low]
  ...)
```

Throws the following error:

```
WARN unsopported form => [p start_low]
```

I am using `doseq` instead.

### PR DESCRIPTION
**Pull request by kiranshila**
Fixes #25

### CODE REVIEW

**Comment by kiranshila** [comment]
I can write some examples and tests if you want

**Comment by nakkaya** [comment]
Tests would be great. It helps users see supported forms.

**Comment by kiranshila** [comment]
Sure! I'm almost done - I noticed my org moved the src block in a weird place too, so I'm fixing that. Additionally, I am going to adjust it such that n-dimensional comprehensions return a flattened list to make it consistent with clojure.

**Comment by kiranshila** [comment]
How do you deal with collisions with names from clojure in `defmacro`? I noticed now that the code I pushed will not work, named as for, but works given any other name.

**Comment by kiranshila** [comment]
Fixes #41 now

**Comment by chr15m** [comment]
@kiranshila legend!

**Comment by kiranshila** [comment]
So if for is written like this
```clojure
      (defmacro comprehension [bindings & body]
        (if (seq bindings)
          `(flatten (map (fn [~(first bindings)] (comprehension ~(drop 2 bindings) ~@body))
                ~(second bindings)))
          `(do ~@body)))
```

And the body of my program is something along the lines of
```clojure
(def output (comprehension [x (list 1 2 3)
                  y (list 4 5 6)]
              (* x y)))

(println output)
```
I successfully get the output
```
(4.0000 5.0000 6.0000 8.0000 10.0000 12.0000 12.0000 15.0000 18.0000)
```

But if the name of the macro itself is `for` - so by changing `comprehension` to `for` in the previous example - the same example program fails here:
```bash
08:45:43 INFO dir => ./
08:45:43 INFO file => ./core.clj
```
before it gets to the c++ stage.

**Comment by nakkaya** [comment]
@kiranshila That is one of the downsides of piggybacking on Clojure for macro expansion. `for` will expand to fully qualified symbol before ferret gets a chance to see it. To make sure it expands to symbol `for` use `~'for` inside the macro.

**Comment by kiranshila** [comment]
Brilliant. I updated that and fixed the unit tests and opened a new PR.

**Pull request merged**
